import { describe, expect, it } from "vitest";
import {
  AGENT_REGISTRY,
  getPolicyBucket,
} from "../../src/agents/agent-registry.js";
import { getToolPolicy } from "../../src/agents/tool-policy.js";
import {
  defaultAgentCards,
  defaultWorkflowAgentCards,
  deriveNlpAgentCards,
} from "../../src/registry/card-loader.js";

describe("agent taxonomy architecture sentinels", () => {
  it("Sentinel L: getToolPolicy buckets match registry policyBucket", () => {
    const expectedByCategory: Record<string, string[]> = {
      read: ["read"],
      write: ["read", "write", "mcp"],
      research: ["read", "mcp"],
    };

    for (const def of AGENT_REGISTRY) {
      const category = getPolicyBucket(def.role)!;

      expect(
        getToolPolicy(def.role).allowedCategories,
        def.role,
      ).toEqual(expectedByCategory[category]);
    }
  });

  it("Sentinel K: AGENT_REGISTRY is exactly the 6 concrete delegate roles (no auto/workflow/control-plane)", () => {
    const roles = AGENT_REGISTRY.map((a) => a.role);
    expect(roles).toHaveLength(6);
    expect([...roles].sort()).toEqual(["docs_researcher", "explorer", "researcher", "reviewer", "test_investigator", "worker"]);
    for (const r of roles) {
      expect(r).not.toBe("auto");
      expect(r.startsWith("workflow.")).toBe(false);
      expect(["operator", "governor", "executor", "verifier"]).not.toContain(r);
    }
  });

  it("Sentinel M: defaultAgentCards is derived; no dead cards; workflow is separate", () => {
    const cards = defaultAgentCards();
    const nlpIds = AGENT_REGISTRY.map((a) => a.role);

    for (const id of nlpIds) {
      expect(
        cards.find((c) => c.id === id),
        `missing derived card ${id}`,
      ).toBeDefined();
    }

    for (const id of [
      "orchestrator.core",
      "planner.graph",
      "memory.curator",
    ]) {
      expect(
        cards.find((c) => c.id === id),
        `${id} must not reappear`,
      ).toBeUndefined();
    }

    const workflow = defaultWorkflowAgentCards();

    expect(workflow).toHaveLength(5);

    for (const card of workflow) {
      expect(card.id.startsWith("workflow.")).toBe(true);
    }

    // Workflow cards must not be generated by the NLP registry projection.
    expect(
      deriveNlpAgentCards().some((c) => c.id.startsWith("workflow.")),
    ).toBe(false);
  });
});
